"""Capture the screenshots the README embeds.

Committed images go stale silently: the UI moves, the numbers change, and the
picture in the README quietly starts describing a version that no longer
exists. So the images are generated by a script rather than pasted in, and the
script starts from a known state -- `demo_reset` -- so the figures in the
screenshots are the same figures the demo produces.

    python scripts/demo_reset.py && python scripts/screenshots.py

Needs Playwright and a local Chrome (`pip install playwright`). It is a dev
tool, not part of the app: nothing in `src/` imports it, and the app has no
browser dependency.
"""
from __future__ import annotations

import socket
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "screenshots"
PORT = 8123

# route, filename, and how long the view needs before it has settled
SHOTS = [
    ("#/dashboard", "01-overview.png", "Overview"),
    ("#/reconcile", "02-reconcile.png", "Reconcile"),
    ("#/exceptions", "03-worklist.png", "Worklist"),
    ("#/runs", "04-accuracy.png", "Accuracy"),
]


def _free(port: int) -> bool:
    with socket.socket() as s:
        return s.connect_ex(("127.0.0.1", port)) != 0


def main() -> int:
    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        print("playwright is not installed: pip install playwright", file=sys.stderr)
        return 1

    OUT.mkdir(parents=True, exist_ok=True)
    server = None
    if _free(PORT):
        server = subprocess.Popen(
            [sys.executable, "-m", "uvicorn", "finance_controller.api:app",
             "--port", str(PORT), "--log-level", "warning"],
            cwd=ROOT, env={**__import__("os").environ, "PYTHONPATH": str(ROOT / "src")},
        )
        for _ in range(60):
            if not _free(PORT):
                break
            time.sleep(0.5)
        else:
            print("the server never came up", file=sys.stderr)
            return 1

    try:
        with sync_playwright() as p:
            browser = p.chromium.launch(channel="chrome")
            page = browser.new_page(viewport={"width": 1440, "height": 940},
                                    device_scale_factor=2)
            for route, name, label in SHOTS:
                page.goto(f"http://127.0.0.1:{PORT}/{route}", wait_until="networkidle")
                page.wait_for_timeout(1400)
                page.screenshot(path=str(OUT / name))
                print(f"  {label:12s} -> docs/screenshots/{name}")
            browser.close()
    finally:
        if server:
            server.terminate()
            server.wait(timeout=10)
    print(f"\n{len(SHOTS)} screenshots written to {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
