"""Razorpay ingestion: live test-mode pull, and fixtures in the same shape.

**Provenance matters more than convenience here.** Data that came from Razorpay
and data we invented must never be confusable, so every batch this module
produces is tagged:

    live_test    pulled from the Razorpay test-mode API with real credentials
    fixture      local fixtures written to match the documented API response
                 shape -- NOT from Razorpay, and never presented as if it were
    synthetic    generated by synth.py for benchmarking

The fixtures below follow the entity shapes in Razorpay's API docs: amounts are
integer paise, timestamps are Unix epochs, ids are prefixed (`pay_`, `rfnd_`,
`setl_`), and refunds carry `payment_id`. That makes the *ingestion path*
genuinely exercised -- epoch parsing, paise-not-rupees, nested notes -- even
where the *credentials* are absent.
"""
from __future__ import annotations

import logging
from dataclasses import dataclass
from datetime import UTC, datetime, timedelta
from typing import Literal

from .config import SETTINGS

log = logging.getLogger("finance_controller.razorpay")

Provenance = Literal["live_test", "fixture", "synthetic"]


class RazorpayUnavailable(RuntimeError):
    """No usable Razorpay credentials, or the API could not be reached."""


@dataclass
class RazorpayBatch:
    provenance: Provenance
    payments: list[dict]
    refunds: list[dict]
    settlements: list[dict]
    note: str = ""

    def as_rows(self) -> dict:
        return {
            "payment": self.payments,
            "refund": self.refunds,
            "settlement": self.settlements,
            "bank": [],
            "ledger": [],
        }

    def summary(self) -> dict:
        return {
            "provenance": self.provenance,
            "payments": len(self.payments),
            "refunds": len(self.refunds),
            "settlements": len(self.settlements),
            "note": self.note,
        }


def fetch_live(count: int = 100, timeout: float = 15.0) -> RazorpayBatch:
    """Pull payments, refunds and settlements from Razorpay **test mode**.

    Raises ``RazorpayUnavailable`` rather than falling back, so a caller can
    never mistake fixture data for live data.
    """
    if not SETTINGS.has_razorpay:
        raise RazorpayUnavailable(
            "RAZORPAY_KEY_ID / RAZORPAY_KEY_SECRET are not set"
        )
    if not SETTINGS.razorpay_key_id.startswith("rzp_test_"):
        # a live key here would pull real customer data into a demo tool
        raise RazorpayUnavailable(
            "refusing to run: key is not a test-mode key (expected rzp_test_ prefix)"
        )
    try:
        import razorpay
    except ImportError as exc:  # pragma: no cover
        raise RazorpayUnavailable("the razorpay package is not installed") from exc

    try:
        client = razorpay.Client(
            auth=(SETTINGS.razorpay_key_id, SETTINGS.razorpay_key_secret)
        )
        client.set_app_details({"title": "ai-finance-controller", "version": "1.0"})
        payments = client.payment.all({"count": count}).get("items", [])
        refunds = _safe(lambda: client.refund.all({"count": count}).get("items", []))
        settlements = _safe(lambda: client.settlement.all({"count": count}).get("items", []))
    except RazorpayUnavailable:
        raise
    except Exception as exc:  # noqa: BLE001 - any SDK/network failure is the same to us
        raise RazorpayUnavailable(
            f"Razorpay test-mode API call failed: {type(exc).__name__}: {exc}"
        ) from exc

    log.info(
        "razorpay test-mode pull: %d payments, %d refunds, %d settlements",
        len(payments), len(refunds), len(settlements),
    )
    return RazorpayBatch(
        provenance="live_test",
        payments=payments,
        refunds=refunds,
        settlements=settlements,
        note="pulled from the Razorpay test-mode API",
    )


def _safe(fn):
    """Some test accounts have no settlements or refunds; that is not an error."""
    try:
        return fn()
    except Exception as exc:  # noqa: BLE001
        log.warning("optional Razorpay endpoint unavailable: %s", exc)
        return []


# --------------------------------------------------------------------------- fixtures


def _epoch(day_offset: int) -> int:
    base = datetime(2026, 7, 1, 10, 30, tzinfo=UTC)
    return int((base + timedelta(days=day_offset)).timestamp())


def fixture_batch() -> RazorpayBatch:
    """A batch in Razorpay's documented API response shape.

    Not from Razorpay. It exists so the ingestion path -- epoch timestamps,
    integer paise, `pay_`/`rfnd_` ids, per-method fee and tax fields, refunds
    that name their payment -- is exercised for real even without credentials.
    """
    payments = [
        _payment("pay_NW3Xk9pQr2LmAb", 1050000, _epoch(0), "card", 21000, 3780, "ORD-88001"),
        _payment("pay_NW3Xm2vTs8KnCd", 499900, _epoch(0), "upi", 0, 0, "ORD-88002"),
        _payment("pay_NW3Xp7wYu4JoEf", 1875050, _epoch(1), "netbanking", 33751, 6075, "ORD-88003"),
        _payment("pay_NW3Xr1zAv6HpGh", 250000, _epoch(1), "wallet", 5000, 900, "ORD-88004"),
        _payment("pay_NW3Xt5bCw9GqIj", 3200000, _epoch(2), "card", 64000, 11520, "ORD-88005"),
        _payment("pay_NW3Xv8dEx3FrKl", 725500, _epoch(2), "upi", 0, 0, "ORD-88006"),
        # an authorized-but-not-captured payment never settles and must not be
        # reported as a missing payout
        _payment("pay_NW3Xy2fGz7EsMn", 150000, _epoch(3), "card", 0, 0, "ORD-88007",
                 status="authorized"),
    ]
    refunds = [
        _refund("rfnd_NW4Aa1bCd2EfGh", "pay_NW3Xk9pQr2LmAb", 300000, _epoch(1)),
        _refund("rfnd_NW4Ae3fGh4IjKl", "pay_NW3Xt5bCw9GqIj", 3200000, _epoch(3)),
    ]
    # These reconcile exactly, on purpose -- a fixture whose arithmetic does not
    # balance tests nothing. Payout 1 covers the two day-0 payments net of the
    # 3,000 refund that landed before it; payout 2 covers the two day-1 payments.
    #   (1050000 + 499900 - 300000) - 21000 - 3780 = 1225120
    #   (1875050 + 250000)          - 38751 - 6975 = 2079324
    settlements = [
        _settlement("setl_NW5Bb1cDe2FgHi", 1225120, 21000, 3780, _epoch(2), "UTR260702001"),
        _settlement("setl_NW5Bf3gHi4JkLm", 2079324, 38751, 6975, _epoch(3), "UTR260703001"),
    ]
    # An authorized-but-uncaptured payment is not money the merchant is owed, so
    # it is excluded rather than reported as a missing payout.
    payments = [p for p in payments if p.get("status") == "captured"]

    return RazorpayBatch(
        provenance="fixture",
        payments=payments,
        refunds=refunds,
        settlements=settlements,
        note=(
            "LOCAL FIXTURE in the documented Razorpay API response shape "
            "(epoch timestamps, integer paise, prefixed ids). NOT pulled from "
            "Razorpay -- no test-mode credentials were available."
        ),
    )


def _payment(pid, amount, created, method, fee, tax, order, status="captured"):
    return {
        "id": pid, "entity": "payment", "amount": amount, "currency": "INR",
        "status": status, "order_id": order, "method": method,
        "captured": status == "captured", "fee": fee, "tax": tax,
        "created_at": created, "description": f"Order {order}",
        "notes": {"channel": "web"},
    }


def _refund(rid, payment_id, amount, created):
    return {
        "id": rid, "entity": "refund", "amount": amount, "currency": "INR",
        "payment_id": payment_id, "status": "processed",
        "speed_processed": "normal", "created_at": created, "notes": {},
    }


def _settlement(sid, amount, fees, tax, created, utr):
    return {
        "id": sid, "entity": "settlement", "amount": amount, "status": "processed",
        "fees": fees, "tax": tax, "utr": utr, "created_at": created,
        "currency": "INR",
    }


def load(prefer_live: bool = True) -> RazorpayBatch:
    """Live test-mode data when credentials allow it, otherwise fixtures.

    The returned batch always states which it is; nothing downstream has to
    guess, and the UI reports it verbatim.
    """
    if prefer_live and SETTINGS.has_razorpay:
        try:
            return fetch_live()
        except RazorpayUnavailable as exc:
            log.warning("falling back to fixtures: %s", exc)
            batch = fixture_batch()
            batch.note = f"{batch.note} (live pull attempted and failed: {exc})"
            return batch
    return fixture_batch()
